name: Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y gcc clang clang-format

    - name: Build Project
      run: make all

    - name: Run Tests
      run: make test

    - name: Code Formatting Check
      run: |  
          make format
          git diff --exit-code --quiet
